-- PARANOIA FRAMEWORK MANDATE: EVERY SINGLE FOREIGN KEY MUST HAVE A CORRESPONDING INDEX. FAILURE TO ADD AN INDEX TO A CASCADING KEY WILL CAUSE PRODUCTION OUTAGES DURING DELETIONS.
-- GDPR MANDATE: EVERY TABLE STORING PII (leads, messages, linkedin data, ai responses) MUST reference workspace_id with ON DELETE CASCADE. Failure to do so violates GDPR Article 17.
-- =================================================================
-- CANONICAL SCHEMA — ELE-IN
-- Last synced with: 016_settings_production.sql
-- DO NOT EDIT this file manually to fix live DB issues.
-- Run migrations instead. This file is for fresh-install only.
-- =================================================================

-- ==============================================================================
-- ELE-IN · SUPABASE PRODUCTION SCHEMA v3 (PostgreSQL 15+)
-- ==============================================================================
-- v2 fixed: #1-#12 + bonus tables.
-- v3 fixes (second audit pass):
--   A. Cookie mechanism unified — BYTEA blob = envelope-encrypted ciphertext;
--   B. RLS WITH CHECK on join-traversal policies (list_members, lead_states,
--   C. accounts (workspace_id, status) index added (plain + partial variants).
--   D. outbox_events.idempotency_key UNIQUE — prevents double-fire on retry.
--   E. accounts.is_active converted to GENERATED ALWAYS from (status = 'ACTIVE').
--   F. sanitize_template_on_publish() trigger strips account refs before publish.
--   G. lead_states.attempts + max_attempts — exponential backoff tracking.
-- Idempotent: safe to re-run.
-- ==============================================================================

-- ============================================================
-- 0. Extensions
-- ============================================================
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";
CREATE EXTENSION IF NOT EXISTS "supabase_vault";
CREATE EXTENSION IF NOT EXISTS "pgsodium";
CREATE EXTENSION IF NOT EXISTS vector;

-- ============================================================
-- 1. Drop legacy objects in reverse dependency order
-- ============================================================
DROP TABLE IF EXISTS public.knowledge_synthesis   CASCADE;
DROP TABLE IF EXISTS public.knowledge_chunks      CASCADE;
DROP TABLE IF EXISTS public.knowledge_assets      CASCADE;
DROP TABLE IF EXISTS public.objections            CASCADE;
DROP TABLE IF EXISTS public.personas              CASCADE;
DROP TABLE IF EXISTS public.outbox_events         CASCADE;
DROP TABLE IF EXISTS public.api_keys              CASCADE;
DROP TABLE IF EXISTS public.proxies               CASCADE;
DROP TABLE IF EXISTS public.subscriptions         CASCADE;
DROP TABLE IF EXISTS public.workspace_members     CASCADE;
DROP TABLE IF EXISTS public.admin_grants          CASCADE;
DROP TABLE IF EXISTS public.audit_log             CASCADE;
DROP TABLE IF EXISTS public.notification_preferences CASCADE;
DROP TABLE IF EXISTS public.workspace_sending_defaults CASCADE;
DROP TABLE IF EXISTS public.workspace_invites     CASCADE;
DROP TABLE IF EXISTS public.user_profiles         CASCADE;
DROP TABLE IF EXISTS public.daily_campaign_stats  CASCADE;
DROP TABLE IF EXISTS public.approval_queue        CASCADE;
DROP TABLE IF EXISTS public.messages              CASCADE;
DROP TABLE IF EXISTS public.action_log            CASCADE;
DROP TABLE IF EXISTS public.action_logs           CASCADE;
DROP TABLE IF EXISTS public.lead_states           CASCADE;
DROP TABLE IF EXISTS public.list_members          CASCADE;
DROP TABLE IF EXISTS public.lead_lists            CASCADE;
DROP TABLE IF EXISTS public.leads                 CASCADE;
DROP TABLE IF EXISTS public.sequence_nodes        CASCADE;
DROP TABLE IF EXISTS public.lead_executions       CASCADE;
DROP TABLE IF EXISTS public.inbox_sync            CASCADE;
DROP TABLE IF EXISTS public.campaigns             CASCADE;
DROP TABLE IF EXISTS public.accounts              CASCADE;
DROP TABLE IF EXISTS public.templates             CASCADE;
DROP TABLE IF EXISTS public.workspaces            CASCADE;

DROP TYPE IF EXISTS public.subscription_tier      CASCADE;
DROP TYPE IF EXISTS public.account_status         CASCADE;
DROP TYPE IF EXISTS public.lead_state_status      CASCADE;
DROP TYPE IF EXISTS public.message_direction      CASCADE;
DROP TYPE IF EXISTS public.approval_status        CASCADE;
DROP TYPE IF EXISTS public.lead_status            CASCADE;
DROP TYPE IF EXISTS public.campaign_status        CASCADE;
DROP TYPE IF EXISTS public.node_type              CASCADE;
DROP TYPE IF EXISTS public.workspace_member_role  CASCADE;
DROP TYPE IF EXISTS public.proxy_status           CASCADE;
DROP TYPE IF EXISTS public.outbox_event_status    CASCADE;
DROP TYPE IF EXISTS public.template_status        CASCADE;
DROP TYPE IF EXISTS template_status               CASCADE;

-- ============================================================
-- 2. Enums
-- ============================================================
CREATE TYPE public.subscription_tier     AS ENUM ('FREE', 'PRO', 'ENTERPRISE');
CREATE TYPE public.account_status        AS ENUM ('ACTIVE', 'DISCONNECTED', 'RATE_LIMITED', 'BANNED');
CREATE TYPE public.lead_state_status     AS ENUM ('pending', 'running', 'completed', 'exited', 'error');
CREATE TYPE public.message_direction     AS ENUM ('inbound', 'outbound');
CREATE TYPE public.approval_status       AS ENUM ('pending', 'approved', 'skipped');
CREATE TYPE public.campaign_status       AS ENUM ('DRAFT', 'ACTIVE', 'PAUSED', 'COMPLETED', 'ARCHIVED');
CREATE TYPE public.lead_status           AS ENUM ('extracted','enriching','enriched','enrolled','connected','replied','disqualified','opted_out');
CREATE TYPE public.workspace_member_role AS ENUM ('owner', 'admin', 'member');
CREATE TYPE public.proxy_status          AS ENUM ('healthy', 'degraded', 'banned', 'disabled');
CREATE TYPE public.outbox_event_status   AS ENUM ('pending', 'delivered', 'failed', 'skipped');
CREATE TYPE public.template_status       AS ENUM ('private', 'pending', 'public', 'rejected');

-- ============================================================
-- 3. user_profiles
-- ============================================================
CREATE TABLE public.user_profiles (
    id            UUID        PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    display_name  TEXT,
    avatar_url    TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
COMMENT ON TABLE public.user_profiles IS 'One row per auth user.';

-- ============================================================
-- 3.5 admin_grants
-- ============================================================
CREATE TABLE public.admin_grants (
    id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id       UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    granted_by    UUID        REFERENCES auth.users(id) ON DELETE SET NULL,
    granted_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    revoked_at    TIMESTAMPTZ,
    revoked_by    UUID        REFERENCES auth.users(id) ON DELETE SET NULL,
    reason        TEXT
);
COMMENT ON TABLE public.admin_grants IS 'Audit trail for superadmin privileges.';
-- ============================================================
-- 4. workspaces
-- ============================================================
CREATE TABLE public.workspaces (
    id                 UUID                     PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_id           UUID                     NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
    name               TEXT                     NOT NULL,
    tier               public.subscription_tier NOT NULL DEFAULT 'FREE',
    require_2fa        BOOLEAN                  NOT NULL DEFAULT false,
    stripe_customer_id TEXT                     UNIQUE,
    status             TEXT                     NOT NULL DEFAULT 'active',
    deletion_requested_at TIMESTAMPTZ,
    created_at         TIMESTAMPTZ              NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMPTZ              NOT NULL DEFAULT NOW()
);
COMMENT ON COLUMN public.workspaces.owner_id IS 'ON DELETE RESTRICT — must transfer ownership before deleting user.';

-- ============================================================
-- 5. workspace_members  [v3-D confirmed: UNIQUE(workspace_id, user_id)]
-- ============================================================
CREATE TABLE public.workspace_members (
    id           UUID                         PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id UUID                         NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
    user_id      UUID                         NOT NULL REFERENCES auth.users(id)        ON DELETE CASCADE,
    role         public.workspace_member_role NOT NULL DEFAULT 'member',
    invited_by   UUID                         REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at   TIMESTAMPTZ                  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_workspace_member UNIQUE (workspace_id, user_id)
);
COMMENT ON TABLE public.workspace_members IS 'UNIQUE(workspace_id, user_id) prevents duplicate invites [v3-D].';

-- ============================================================
-- 5.1 workspace_invites
-- ============================================================
CREATE TABLE public.workspace_invites (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id uuid NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
    email text NOT NULL,
    role public.workspace_member_role NOT NULL DEFAULT 'member',
    invited_by uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    token text NOT NULL UNIQUE,
    status text NOT NULL DEFAULT 'pending',
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT uq_pending_invite UNIQUE (workspace_id, email)
);

-- ============================================================
-- 5.2 workspace_sending_defaults
-- ============================================================
CREATE TABLE public.workspace_sending_defaults (
    workspace_id uuid PRIMARY KEY REFERENCES public.workspaces(id) ON DELETE CASCADE,
    default_daily_connection_limit integer NOT NULL DEFAULT 20,
    default_daily_message_limit integer NOT NULL DEFAULT 40,
    default_warmup_target_days integer NOT NULL DEFAULT 30,
    default_working_hours_start time NOT NULL DEFAULT '08:00',
    default_working_hours_end time NOT NULL DEFAULT '18:00',
    default_timezone text NOT NULL DEFAULT 'UTC',
    weekend_sending_enabled boolean NOT NULL DEFAULT false,
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);

-- ============================================================
-- 5.3 notification_preferences
-- ============================================================
CREATE TABLE public.notification_preferences (
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    workspace_id uuid NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
    event_type text NOT NULL,
    channel text NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    PRIMARY KEY (user_id, workspace_id, event_type, channel)
);

-- ============================================================
-- 5.4 audit_log
-- ============================================================
CREATE TABLE public.audit_log (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id uuid NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
    actor_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    action text NOT NULL,
    target_type text NOT NULL,
    target_id uuid,
    before_state jsonb,
    after_state jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now()
);
CREATE INDEX idx_audit_log_workspace_created ON public.audit_log (workspace_id, created_at DESC);

-- ============================================================
-- 6. subscriptions
-- ============================================================
CREATE TABLE public.subscriptions (
    id                     UUID                     PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id           UUID                     NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
    stripe_subscription_id TEXT                     NOT NULL UNIQUE,
    stripe_price_id        TEXT,
    status                 TEXT                     NOT NULL,
    tier                   public.subscription_tier NOT NULL DEFAULT 'FREE',
    current_period_start   TIMESTAMPTZ,
    current_period_end     TIMESTAMPTZ,
    cancel_at_period_end   BOOLEAN                  NOT NULL DEFAULT FALSE,
    canceled_at            TIMESTAMPTZ,
    trial_end              TIMESTAMPTZ,
    raw_stripe_event       JSONB,
    created_at             TIMESTAMPTZ              NOT NULL DEFAULT NOW(),
    updated_at             TIMESTAMPTZ              NOT NULL DEFAULT NOW()
);
COMMENT ON COLUMN public.subscriptions.raw_stripe_event IS 'Last raw Stripe webhook payload for debugging. Do not rely on for business logic.';

-- ============================================================
-- 7. proxies
-- ============================================================
CREATE TABLE public.proxies (
    id              UUID                PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id    UUID                REFERENCES public.workspaces(id) ON DELETE CASCADE,
    provider        TEXT                NOT NULL,
    host            TEXT                NOT NULL,
    port            INTEGER             NOT NULL,
    username        TEXT,
    secret_ref      TEXT,
    protocol        TEXT                NOT NULL DEFAULT 'http',
    country_code    CHAR(2),
    status          public.proxy_status NOT NULL DEFAULT 'healthy',
    last_checked_at TIMESTAMPTZ,
    created_at      TIMESTAMPTZ         NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ         NOT NULL DEFAULT NOW()
);
COMMENT ON COLUMN public.proxies.secret_ref IS 'KMS/Vault ref for proxy credentials. NEVER store the password here.';

-- ============================================================
-- 8. accounts
--
-- [v3-A] Cookie storage — SINGLE mechanism (envelope encryption):
--   session_cookies_encrypted BYTEA = AES-256-GCM ciphertext (blob encrypted with data key)
--   These are not two competing approaches — they are two halves of one mechanism.
--   Without KMS yet: store UTF-8 bytes in session_cookies_encrypted, leave ref NULL.
--
-- [v3-E] is_active is a GENERATED column derived from status.
--   Write status; is_active stays in sync automatically. Cannot drift.
-- ============================================================
CREATE TABLE public.accounts (
    id                        UUID                  PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id              UUID                  NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
    proxy_id                  UUID                  REFERENCES public.proxies(id)             ON DELETE SET NULL,
    name                      TEXT                  NOT NULL,
    linkedin_profile_url      TEXT,
    cookie_secret_ref         UUID,
    session_cookies_encrypted BYTEA,
    is_warmup                 BOOLEAN               NOT NULL DEFAULT FALSE,
    warmup_start_date         TIMESTAMPTZ,
    warmup_target_days        INTEGER               NOT NULL DEFAULT 30,
    warmup_max_connections    INTEGER               NOT NULL DEFAULT 20,
    warmup_max_messages       INTEGER               NOT NULL DEFAULT 40,
    status                    public.account_status NOT NULL DEFAULT 'ACTIVE',
    is_active                 BOOLEAN               NOT NULL GENERATED ALWAYS AS (status = 'ACTIVE') STORED,
    last_health_check_at      TIMESTAMPTZ,
    cookie_expires_at         TIMESTAMPTZ,
    session_locked_until      TIMESTAMPTZ,
    manual_send_suspected     BOOLEAN               DEFAULT false,
    manual_send_suspected_at  TIMESTAMPTZ,
    created_at                TIMESTAMPTZ           NOT NULL DEFAULT NOW(),
    updated_at                TIMESTAMPTZ           NOT NULL DEFAULT NOW(),

    CONSTRAINT accounts_workspace_linkedin_unique UNIQUE (workspace_id, linkedin_profile_url)
);
COMMENT ON COLUMN public.accounts.is_active IS '[v3-E] GENERATED ALWAYS AS (status = ACTIVE). Write status; read either. Cannot drift.';

-- ============================================================
-- 8.1 account_health_checks
-- ============================================================
CREATE TABLE public.account_health_checks (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    account_id uuid NOT NULL REFERENCES public.accounts(id) ON DELETE CASCADE,
    check_type text NOT NULL CHECK (check_type IN ('session_valid', 'cookie_freshness', 'profile_reachable', 'restriction_detected')),
    result text NOT NULL CHECK (result IN ('pass', 'warn', 'fail')),
    detail jsonb NOT NULL DEFAULT '{}',
    checked_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================
-- 8.2 account_reconnect_requests
-- ============================================================
CREATE TABLE public.account_reconnect_requests (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    account_id uuid NOT NULL REFERENCES public.accounts(id) ON DELETE CASCADE,
    requested_by uuid NOT NULL REFERENCES auth.users(id),
    token text NOT NULL UNIQUE,
    status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'completed', 'expired')),
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================
-- 8.3 account_connection_sessions
-- ============================================================
CREATE TABLE public.account_connection_sessions (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id uuid NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
    initiated_by uuid NOT NULL REFERENCES auth.users(id),
    token text NOT NULL UNIQUE,
    status text NOT NULL DEFAULT 'awaiting_extension' CHECK (status IN ('awaiting_extension', 'completed', 'expired')),
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================
-- 8.4 account_tags
-- ============================================================
CREATE TABLE public.account_tags (
    account_id uuid NOT NULL REFERENCES public.accounts(id) ON DELETE CASCADE,
    tag text NOT NULL CHECK (length(tag) > 0 AND length(tag) <= 50),
    PRIMARY KEY (account_id, tag)
);

-- ============================================================
-- 8.5 account_limit_overrides
-- ============================================================
CREATE TABLE public.account_limit_overrides (
    account_id uuid REFERENCES public.accounts(id) ON DELETE CASCADE,
    action_type text NOT NULL,
    custom_limit integer NOT NULL,
    expires_at timestamptz,
    created_at timestamptz DEFAULT now(),
    PRIMARY KEY (account_id, action_type)
);

ALTER TABLE public.account_limit_overrides ENABLE ROW LEVEL SECURITY;

-- account_limit_overrides inherits workspace isolation through the parent accounts table
CREATE POLICY "account_limit_overrides_ws" ON public.account_limit_overrides
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.accounts a
      WHERE a.id = account_limit_overrides.account_id
        AND a.workspace_id = ANY(public.my_workspace_ids())
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.accounts a
      WHERE a.id = account_limit_overrides.account_id
        AND a.workspace_id = ANY(public.my_workspace_ids())
    )
  );

-- ============================================================
-- 9. campaigns
-- ============================================================
CREATE TABLE public.campaigns (
    id                      UUID                   PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id            UUID                   NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
    name                    TEXT                   NOT NULL,
    status                  public.campaign_status NOT NULL DEFAULT 'DRAFT',
    nodes_json              JSONB                  NOT NULL DEFAULT '[]',
    edges_json              JSONB                  NOT NULL DEFAULT '[]',
    sender_account_ids_json JSONB                  NOT NULL DEFAULT '[]',
    metadata                JSONB                  NOT NULL DEFAULT '{}',
    created_at              TIMESTAMPTZ            NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ            NOT NULL DEFAULT NOW()
);

-- ============================================================
-- 10. leads
-- ============================================================
CREATE TABLE public.leads (
    id                  UUID               PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id        UUID               NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
    first_name          TEXT,
    last_name           TEXT,
    linkedin_url        TEXT               NOT NULL,
    company_name        TEXT,
    email               TEXT,
    domain              TEXT,
    job_title           TEXT,
    company_description TEXT,
    location            TEXT,
    industry            TEXT,
    mutual_connections  TEXT,
    enrichment_source   TEXT               DEFAULT 'csv',
    status              public.lead_status NOT NULL DEFAULT 'extracted',
    metadata            JSONB              NOT NULL DEFAULT '{}',
    created_at          TIMESTAMPTZ        NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ        NOT NULL DEFAULT NOW(),
    UNIQUE (workspace_id, linkedin_url)
);
COMMENT ON TABLE public.leads IS 'UNIQUE(workspace_id, linkedin_url) prevents duplicate ingestion [v3-C confirmed].';

-- ============================================================
-- 11. lead_lists
-- ============================================================
CREATE TABLE public.lead_lists (
    id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id UUID        NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
    name         TEXT        NOT NULL,
    type         TEXT        NOT NULL DEFAULT 'csv',
    row_count    INTEGER     NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- 12. list_members
-- ============================================================
CREATE TABLE public.list_members (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    list_id        UUID NOT NULL REFERENCES public.lead_lists(id) ON DELETE CASCADE,
    opportunity_id UUID NOT NULL REFERENCES public.leads(id)      ON DELETE CASCADE,
    UNIQUE (list_id, opportunity_id)
);

-- ============================================================
-- 13. lead_states
-- [v3-G] attempts + max_attempts for exponential backoff
-- ============================================================
CREATE TABLE public.lead_states (
    id              UUID                     PRIMARY KEY DEFAULT gen_random_uuid(),
    campaign_id     UUID                     NOT NULL REFERENCES public.campaigns(id) ON DELETE CASCADE,
    opportunity_id  UUID                     NOT NULL REFERENCES public.leads(id)     ON DELETE CASCADE,
    current_node_id TEXT,
    status          public.lead_state_status NOT NULL DEFAULT 'pending',
    next_run_at     TIMESTAMPTZ,
    variables_json  JSONB                    NOT NULL DEFAULT '{}',
    error_reason    TEXT,
    attempts        INTEGER                  NOT NULL DEFAULT 0,
    max_attempts    INTEGER                  NOT NULL DEFAULT 5,
    updated_at      TIMESTAMPTZ              NOT NULL DEFAULT NOW(),
    created_at      TIMESTAMPTZ              NOT NULL DEFAULT NOW(),
    UNIQUE (campaign_id, opportunity_id)
);
COMMENT ON COLUMN public.lead_states.attempts     IS '[v3-G] Incremented by worker on each retry.';
COMMENT ON COLUMN public.lead_states.max_attempts IS '[v3-G] Worker sets status=error when attempts >= max_attempts. Default 5.';

-- ============================================================
-- 15. action_log  (single table, response_payload absent by design)
-- ============================================================
CREATE TABLE public.action_log (
    id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id  UUID        NOT NULL REFERENCES public.workspaces(id)  ON DELETE CASCADE,
    account_id    UUID        REFERENCES public.accounts(id)              ON DELETE SET NULL,
    lead_state_id UUID        REFERENCES public.lead_states(id)           ON DELETE SET NULL,
    action_type   TEXT        NOT NULL,
    result        TEXT        NOT NULL DEFAULT 'success',
    error_detail  TEXT,
    metadata      JSONB       NOT NULL DEFAULT '{}',
    executed_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
COMMENT ON TABLE public.action_log IS 'APPEND-ONLY. response_payload absent by design — LinkedIn responses may contain PII/tokens.';

-- ============================================================
-- 16. messages
-- ============================================================
CREATE TABLE public.messages (
    id                UUID                     PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id      UUID                     NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
    account_id        UUID                     REFERENCES public.accounts(id)             ON DELETE SET NULL,
    lead_id           UUID                     REFERENCES public.leads(id)                ON DELETE SET NULL,
    sender_name       TEXT                     NOT NULL,
    message_text      TEXT                     NOT NULL,
    direction         public.message_direction NOT NULL,
    intent            TEXT                     NOT NULL DEFAULT 'unknown',
    intent_confidence FLOAT                    NOT NULL DEFAULT 0.0,
    created_at        TIMESTAMPTZ              NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ              NOT NULL DEFAULT NOW()
);

-- ============================================================
-- 17. approval_queue
-- ============================================================
CREATE TABLE public.approval_queue (
    id                   UUID                   PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id         UUID                   NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
    account_id           UUID                   REFERENCES public.accounts(id)             ON DELETE SET NULL,
    sender_name          TEXT                   NOT NULL,
    thread_messages_json JSONB                  NOT NULL DEFAULT '[]',
    intent               TEXT                   NOT NULL DEFAULT 'unknown',
    heat_score           FLOAT                  NOT NULL DEFAULT 0.0,
    ai_draft             TEXT,
    status               public.approval_status NOT NULL DEFAULT 'pending',
    reviewed_at          TIMESTAMPTZ,
    created_at           TIMESTAMPTZ            NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ            NOT NULL DEFAULT NOW()
);

-- ============================================================
-- 18. daily_campaign_stats  [v3-D confirmed: UNIQUE(campaign_id, stat_date)]
-- ============================================================
CREATE TABLE public.daily_campaign_stats (
    id               UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id     UUID    NOT NULL REFERENCES public.workspaces(id)  ON DELETE CASCADE,
    campaign_id      UUID    NOT NULL REFERENCES public.campaigns(id)   ON DELETE CASCADE,
    stat_date        DATE    NOT NULL,
    connections_sent INTEGER NOT NULL DEFAULT 0,
    messages_sent    INTEGER NOT NULL DEFAULT 0,
    accepted         INTEGER NOT NULL DEFAULT 0,
    replied          INTEGER NOT NULL DEFAULT 0,
    UNIQUE (campaign_id, stat_date)
);

-- ============================================================
-- 19. templates  [v3-F: sanitize trigger strips account refs on publish]
-- ============================================================
CREATE TABLE public.templates (
    id           UUID                   PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id UUID                   REFERENCES public.workspaces(id) ON DELETE CASCADE,
    name         TEXT                   NOT NULL,
    description  TEXT,
    nodes_json   JSONB                  NOT NULL DEFAULT '[]',
    edges_json   JSONB                  NOT NULL DEFAULT '[]',
    status       public.template_status NOT NULL DEFAULT 'private',
    tags         TEXT[]                 DEFAULT '{}',
    downloads    INTEGER                NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ            NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ            NOT NULL DEFAULT NOW()
);
COMMENT ON TABLE public.templates IS '[v3-F] nodes_json sanitized of workspace account refs on publish via before-update trigger.';

-- ============================================================
-- 20. outbox_events  [v3-D: idempotency_key UNIQUE prevents double-fire]
-- ============================================================
CREATE TABLE public.outbox_events (
    id              UUID                       PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id    UUID                       NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
    event_type      TEXT                       NOT NULL,
    payload         JSONB                      NOT NULL DEFAULT '{}',
    idempotency_key TEXT                       UNIQUE,
    status          public.outbox_event_status NOT NULL DEFAULT 'pending',
    attempts        INTEGER                    NOT NULL DEFAULT 0,
    last_error      TEXT,
    deliver_at      TIMESTAMPTZ                NOT NULL DEFAULT NOW(),
    delivered_at    TIMESTAMPTZ,
    created_at      TIMESTAMPTZ                NOT NULL DEFAULT NOW()
);
COMMENT ON COLUMN public.outbox_events.idempotency_key IS '[v3-D] Set by caller, e.g. action_log_id::text || '':'' || event_type. ON CONFLICT DO NOTHING in dispatcher.';

-- ============================================================
-- 21. api_keys
-- ============================================================
CREATE TABLE public.api_keys (
    id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id UUID        NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
    name         TEXT        NOT NULL,
    key_hash     TEXT        NOT NULL UNIQUE,
    key_prefix   TEXT        NOT NULL,
    last_used_at TIMESTAMPTZ,
    expires_at   TIMESTAMPTZ,
    is_active    BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
COMMENT ON TABLE public.api_keys IS 'key_hash = SHA-256 only. Plaintext never stored.';

-- ============================================================
-- INDEXES
-- ============================================================
CREATE INDEX ON public.workspace_members (user_id);
CREATE INDEX ON public.workspace_members (workspace_id);

CREATE INDEX ON public.admin_grants (user_id);

CREATE INDEX ON public.subscriptions (workspace_id);
CREATE INDEX ON public.subscriptions (status, current_period_end);

CREATE INDEX ON public.proxies (workspace_id);
CREATE INDEX ON public.proxies (status) WHERE status = 'healthy';

-- [v3-C] accounts: plain + partial variants
CREATE INDEX ON public.accounts (workspace_id);
CREATE INDEX idx_accounts_workspace_status ON public.accounts (workspace_id, status) WHERE status = 'ACTIVE';
CREATE INDEX ON public.accounts (proxy_id);

CREATE INDEX idx_account_health_checks_account_time ON public.account_health_checks (account_id, checked_at DESC);
CREATE INDEX idx_reconnect_requests_token ON public.account_reconnect_requests (token) WHERE status = 'pending';
CREATE INDEX idx_connection_sessions_token ON public.account_connection_sessions (token) WHERE status = 'awaiting_extension';
CREATE INDEX idx_account_tags_tag ON public.account_tags (tag);


CREATE INDEX ON public.campaigns (workspace_id, status);

CREATE INDEX ON public.leads (workspace_id);
CREATE INDEX ON public.leads (workspace_id, status);
CREATE INDEX ON public.leads USING GIN (first_name gin_trgm_ops);
CREATE INDEX ON public.leads USING GIN (last_name  gin_trgm_ops);

CREATE INDEX ON public.lead_lists  (workspace_id);
CREATE INDEX ON public.list_members (list_id);
CREATE INDEX ON public.list_members (opportunity_id);

-- [v3-C confirmed] Core scheduler query
CREATE INDEX ON public.lead_states (status, next_run_at) WHERE status IN ('pending', 'running');
CREATE INDEX ON public.lead_states (campaign_id, status);
-- [v3-G] Retry index: find error leads with remaining attempts
CREATE INDEX ON public.lead_states (status, attempts) WHERE status = 'error';

CREATE INDEX ON public.action_log (workspace_id, executed_at DESC);
CREATE INDEX ON public.action_log (account_id, action_type, executed_at DESC);
CREATE INDEX ON public.action_log (account_id, executed_at DESC);
CREATE INDEX ON public.action_log (lead_state_id) WHERE lead_state_id IS NOT NULL;

CREATE INDEX ON public.messages (workspace_id, created_at DESC);
CREATE INDEX ON public.messages (account_id, sender_name);
CREATE INDEX ON public.messages (workspace_id, direction, created_at DESC);
CREATE INDEX ON public.messages (lead_id) WHERE lead_id IS NOT NULL;

CREATE INDEX ON public.approval_queue (workspace_id, status, heat_score DESC);

CREATE INDEX ON public.daily_campaign_stats (campaign_id, stat_date DESC);
CREATE INDEX ON public.daily_campaign_stats (workspace_id, stat_date DESC);

CREATE INDEX ON public.outbox_events (status, deliver_at) WHERE status = 'pending';
CREATE INDEX ON public.outbox_events (workspace_id);

CREATE INDEX ON public.api_keys (workspace_id, is_active) WHERE is_active = TRUE;

CREATE INDEX ON public.templates (workspace_id);
CREATE INDEX ON public.templates (status) WHERE status = 'public';

-- ============================================================
-- FUNCTIONS
-- ============================================================
CREATE OR REPLACE FUNCTION public.cleanup_expired_account_sessions()
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
  UPDATE public.account_connection_sessions SET status = 'expired'
    WHERE status = 'awaiting_extension' AND expires_at < now();
  UPDATE public.account_reconnect_requests SET status = 'expired'
    WHERE status = 'pending' AND expires_at < now();
END;
$$;

CREATE OR REPLACE FUNCTION public.store_account_secret(p_secret text)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_secret_id uuid;
BEGIN
    SELECT vault.create_secret(p_secret, 'Account DEK') INTO v_secret_id;
    RETURN v_secret_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_decrypted_account_payload(p_account_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_cookie_secret_ref uuid;
    v_session_cookies_encrypted bytea;
    v_dek text := null;
BEGIN
    SELECT cookie_secret_ref, session_cookies_encrypted
    INTO v_cookie_secret_ref, v_session_cookies_encrypted
    FROM public.accounts
    WHERE id = p_account_id;

    IF v_cookie_secret_ref IS NOT NULL THEN
        SELECT secret INTO v_dek
        FROM vault.decrypted_secrets
        WHERE id = v_cookie_secret_ref;
    END IF;

    RETURN jsonb_build_object(
        'cookie_secret_ref', v_cookie_secret_ref,
        'dek', v_dek,
        'session_cookies_encrypted', encode(v_session_cookies_encrypted, 'base64')
    );
END;
$$;

CREATE OR REPLACE FUNCTION public.get_account_action_limit(p_account_id uuid, p_action_type text)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_override_limit integer;
    v_global_limit integer;
    v_is_warmup boolean;
    v_warmup_start_date timestamptz;
    v_warmup_limit integer;
BEGIN
    -- Logic Step 1: Look for an active override
    SELECT custom_limit INTO v_override_limit
    FROM public.account_limit_overrides
    WHERE account_id = p_account_id
      AND action_type = p_action_type
      AND (expires_at IS NULL OR expires_at > now());

    IF v_override_limit IS NOT NULL THEN
        RETURN v_override_limit;
    END IF;

    -- Logic Step 2: Fetch global max
    SELECT daily_limit INTO v_global_limit
    FROM public.action_type_limits
    WHERE action_type = p_action_type;

    IF v_global_limit IS NULL THEN
        RETURN 0;
    END IF;

    -- Logic Step 3: Check is_warmup
    SELECT is_warmup, warmup_start_date INTO v_is_warmup, v_warmup_start_date
    FROM public.accounts
    WHERE id = p_account_id;

    IF v_is_warmup = true AND p_action_type IN ('connection_request', 'message', 'inmail') THEN
        v_warmup_limit := 15 + ( GREATEST(0, (CURRENT_DATE - warmup_start_date::date)) / 3 ) * 5;
        RETURN LEAST(v_warmup_limit, v_global_limit);
    END IF;

    RETURN v_global_limit;
END;
$$;

-- ============================================================
-- TRIGGER FUNCTIONS
-- ============================================================

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$;

CREATE OR REPLACE FUNCTION public.cleanup_vault_secret()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    IF OLD.cookie_secret_ref IS NOT NULL THEN
        DELETE FROM vault.secrets WHERE id = OLD.cookie_secret_ref;
    END IF;
    RETURN OLD;
END;
$$;

CREATE TRIGGER user_profiles_updated_at     BEFORE UPDATE ON public.user_profiles        FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER workspaces_updated_at        BEFORE UPDATE ON public.workspaces           FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER subscriptions_updated_at     BEFORE UPDATE ON public.subscriptions        FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER proxies_updated_at           BEFORE UPDATE ON public.proxies              FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER accounts_updated_at          BEFORE UPDATE ON public.accounts             FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER accounts_cleanup_vault_secret AFTER DELETE ON public.accounts             FOR EACH ROW EXECUTE FUNCTION public.cleanup_vault_secret();
CREATE TRIGGER campaigns_updated_at         BEFORE UPDATE ON public.campaigns            FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER leads_updated_at             BEFORE UPDATE ON public.leads                FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER lead_lists_updated_at        BEFORE UPDATE ON public.lead_lists           FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER lead_states_updated_at       BEFORE UPDATE ON public.lead_states          FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER messages_updated_at          BEFORE UPDATE ON public.messages             FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER approval_queue_updated_at    BEFORE UPDATE ON public.approval_queue       FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER templates_updated_at         BEFORE UPDATE ON public.templates            FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- [v3-F] Strip workspace-specific account references when template moves to public/pending
CREATE OR REPLACE FUNCTION public.sanitize_template_on_publish()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.status IN ('pending', 'public') AND (OLD.status IS DISTINCT FROM NEW.status OR TG_OP = 'INSERT') THEN
        NEW.nodes_json := (
            SELECT COALESCE(jsonb_agg(
                (node - 'senderAccountId' - 'accountId' - 'account_id' - 'senderAccountIds')
                || CASE
                     WHEN node ? 'data' THEN jsonb_build_object('data',
                         (node->'data') - 'senderAccountId' - 'accountId' - 'account_id' - 'senderAccountIds'
                     )
                     ELSE '{}'::jsonb
                   END
            ), '[]'::jsonb)
            FROM jsonb_array_elements(NEW.nodes_json) AS node
        );
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER templates_sanitize_on_publish
    BEFORE INSERT OR UPDATE ON public.templates
    FOR EACH ROW EXECUTE FUNCTION public.sanitize_template_on_publish();

-- Daily stats rollup on action_log insert
CREATE OR REPLACE FUNCTION public.update_daily_campaign_stats()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
    v_campaign_id  UUID;
    v_workspace_id UUID;
    v_stat_date    DATE := DATE(NEW.executed_at AT TIME ZONE 'UTC');
BEGIN
    IF NEW.lead_state_id IS NOT NULL THEN
        SELECT ls.campaign_id, c.workspace_id
          INTO v_campaign_id, v_workspace_id
          FROM public.lead_states ls
          JOIN public.campaigns   c ON c.id = ls.campaign_id
         WHERE ls.id = NEW.lead_state_id;
    ELSE
        v_workspace_id := NEW.workspace_id;
    END IF;

    IF v_campaign_id IS NULL THEN RETURN NEW; END IF;

    INSERT INTO public.daily_campaign_stats
        (workspace_id, campaign_id, stat_date, connections_sent, messages_sent)
    VALUES (
        v_workspace_id, v_campaign_id, v_stat_date,
        CASE WHEN NEW.action_type ILIKE '%connection%' THEN 1 ELSE 0 END,
        CASE WHEN NEW.action_type IN ('send_message','send_inmail','send_paid_inmail','send_voice_note','send_message_with_doc','send_message_with_image') THEN 1 ELSE 0 END
    )
    ON CONFLICT (campaign_id, stat_date) DO UPDATE SET
        connections_sent = public.daily_campaign_stats.connections_sent + EXCLUDED.connections_sent,
        messages_sent    = public.daily_campaign_stats.messages_sent    + EXCLUDED.messages_sent;

    RETURN NEW;
END;
$$;

CREATE TRIGGER action_log_rollup_stats
    AFTER INSERT ON public.action_log
    FOR EACH ROW EXECUTE FUNCTION public.update_daily_campaign_stats();


    AFTER INSERT ON public.action_log
    FOR EACH ROW EXECUTE FUNCTION public.increment_daily_usage();

-- Sync lead_lists.row_count
CREATE OR REPLACE FUNCTION public.sync_list_row_count()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        UPDATE public.lead_lists SET row_count = row_count + 1 WHERE id = NEW.list_id;
    ELSIF TG_OP = 'DELETE' THEN
        UPDATE public.lead_lists SET row_count = GREATEST(row_count - 1, 0) WHERE id = OLD.list_id;
    END IF;
    RETURN NULL;
END;
$$;

CREATE TRIGGER list_members_sync_count
    AFTER INSERT OR DELETE ON public.list_members
    FOR EACH ROW EXECUTE FUNCTION public.sync_list_row_count();

-- ============================================================
-- ROW LEVEL SECURITY
-- [v3-B] WITH CHECK on ALL policies — column default != security boundary
-- ============================================================

CREATE OR REPLACE FUNCTION public.my_workspace_ids()
RETURNS SETOF UUID LANGUAGE sql STABLE SECURITY DEFINER AS $$
    SELECT workspace_id FROM public.workspace_members WHERE user_id = auth.uid();
$$;

CREATE OR REPLACE FUNCTION public.get_my_workspace_id()
RETURNS UUID LANGUAGE sql STABLE SECURITY DEFINER AS $$
    SELECT workspace_id FROM public.workspace_members WHERE user_id = auth.uid() ORDER BY created_at ASC LIMIT 1;
$$;

ALTER TABLE public.user_profiles        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_grants         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workspaces           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workspace_members    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscriptions        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.proxies              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.accounts             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.account_health_checks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.account_reconnect_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.account_connection_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.account_tags         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campaigns            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leads                ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lead_lists           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.list_members         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lead_states          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.action_log           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.approval_queue       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_campaign_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.templates            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.outbox_events        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.api_keys             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workspace_invites    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workspace_sending_defaults ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notification_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_log            ENABLE ROW LEVEL SECURITY;

CREATE POLICY user_profiles_self        ON public.user_profiles        FOR ALL USING (id = auth.uid()) WITH CHECK (id = auth.uid());
CREATE POLICY admin_grants_self         ON public.admin_grants         FOR SELECT USING (user_id = auth.uid());
CREATE POLICY workspaces_member         ON public.workspaces           FOR ALL USING (id IN (SELECT public.my_workspace_ids())) WITH CHECK (id IN (SELECT public.my_workspace_ids()));
CREATE POLICY workspace_members_ws      ON public.workspace_members    FOR ALL USING (workspace_id IN (SELECT public.my_workspace_ids())) WITH CHECK (workspace_id IN (SELECT public.my_workspace_ids()));
CREATE POLICY subscriptions_ws          ON public.subscriptions        FOR ALL USING (workspace_id IN (SELECT public.my_workspace_ids())) WITH CHECK (workspace_id IN (SELECT public.my_workspace_ids()));
CREATE POLICY proxies_ws                ON public.proxies               FOR ALL USING (workspace_id IN (SELECT public.my_workspace_ids()) OR workspace_id IS NULL) WITH CHECK (workspace_id IN (SELECT public.my_workspace_ids()));
CREATE POLICY accounts_ws               ON public.accounts             FOR ALL USING (workspace_id IN (SELECT public.my_workspace_ids())) WITH CHECK (workspace_id IN (SELECT public.my_workspace_ids()));

CREATE POLICY account_health_checks_ws
    ON public.account_health_checks FOR ALL
    USING (account_id IN (SELECT id FROM public.accounts WHERE workspace_id IN (SELECT public.my_workspace_ids())))
    WITH CHECK (account_id IN (SELECT id FROM public.accounts WHERE workspace_id IN (SELECT public.my_workspace_ids())));

CREATE POLICY account_reconnect_requests_ws
    ON public.account_reconnect_requests FOR ALL
    USING (account_id IN (SELECT id FROM public.accounts WHERE workspace_id IN (SELECT public.my_workspace_ids())))
    WITH CHECK (account_id IN (SELECT id FROM public.accounts WHERE workspace_id IN (SELECT public.my_workspace_ids())));

CREATE POLICY account_connection_sessions_ws
    ON public.account_connection_sessions FOR ALL
    USING (workspace_id IN (SELECT public.my_workspace_ids()))
    WITH CHECK (workspace_id IN (SELECT public.my_workspace_ids()));

CREATE POLICY account_tags_ws
    ON public.account_tags FOR ALL
    USING (account_id IN (SELECT id FROM public.accounts WHERE workspace_id IN (SELECT public.my_workspace_ids())))
    WITH CHECK (account_id IN (SELECT id FROM public.accounts WHERE workspace_id IN (SELECT public.my_workspace_ids())));

CREATE POLICY campaigns_ws              ON public.campaigns            FOR ALL USING (workspace_id IN (SELECT public.my_workspace_ids())) WITH CHECK (workspace_id IN (SELECT public.my_workspace_ids()));
CREATE POLICY leads_ws                  ON public.leads                FOR ALL USING (workspace_id IN (SELECT public.my_workspace_ids())) WITH CHECK (workspace_id IN (SELECT public.my_workspace_ids()));
CREATE POLICY lead_lists_ws             ON public.lead_lists           FOR ALL USING (workspace_id IN (SELECT public.my_workspace_ids())) WITH CHECK (workspace_id IN (SELECT public.my_workspace_ids()));
CREATE POLICY action_log_ws             ON public.action_log           FOR ALL USING (workspace_id IN (SELECT public.my_workspace_ids())) WITH CHECK (workspace_id IN (SELECT public.my_workspace_ids()));
CREATE POLICY messages_ws               ON public.messages             FOR ALL USING (workspace_id IN (SELECT public.my_workspace_ids())) WITH CHECK (workspace_id IN (SELECT public.my_workspace_ids()));
CREATE POLICY approval_queue_ws         ON public.approval_queue       FOR ALL USING (workspace_id IN (SELECT public.my_workspace_ids())) WITH CHECK (workspace_id IN (SELECT public.my_workspace_ids()));
CREATE POLICY daily_stats_ws            ON public.daily_campaign_stats FOR ALL USING (workspace_id IN (SELECT public.my_workspace_ids())) WITH CHECK (workspace_id IN (SELECT public.my_workspace_ids()));
CREATE POLICY outbox_events_ws          ON public.outbox_events        FOR ALL USING (workspace_id IN (SELECT public.my_workspace_ids())) WITH CHECK (workspace_id IN (SELECT public.my_workspace_ids()));
CREATE POLICY api_keys_ws               ON public.api_keys             FOR ALL USING (workspace_id IN (SELECT public.my_workspace_ids())) WITH CHECK (workspace_id IN (SELECT public.my_workspace_ids()));

-- [v3-B] Join-traversal policies now have WITH CHECK
CREATE POLICY list_members_ws
    ON public.list_members FOR ALL
    USING (list_id IN (SELECT id FROM public.lead_lists WHERE workspace_id IN (SELECT public.my_workspace_ids())))
    WITH CHECK (list_id IN (SELECT id FROM public.lead_lists WHERE workspace_id IN (SELECT public.my_workspace_ids())));

CREATE POLICY lead_states_ws
    ON public.lead_states FOR ALL
    USING (campaign_id IN (SELECT id FROM public.campaigns WHERE workspace_id IN (SELECT public.my_workspace_ids())))
    WITH CHECK (campaign_id IN (SELECT id FROM public.campaigns WHERE workspace_id IN (SELECT public.my_workspace_ids())));

CREATE POLICY account_daily_usage_ws
    ON public.account_daily_usage FOR ALL
    USING (account_id IN (SELECT id FROM public.accounts WHERE workspace_id IN (SELECT public.my_workspace_ids())))
    WITH CHECK (account_id IN (SELECT id FROM public.accounts WHERE workspace_id IN (SELECT public.my_workspace_ids())));

-- Templates: public = readable by all; write/update = workspace scoped
CREATE POLICY templates_read   ON public.templates FOR SELECT USING (status = 'public' OR workspace_id IN (SELECT public.my_workspace_ids()));
CREATE POLICY templates_write  ON public.templates FOR INSERT WITH CHECK (workspace_id IN (SELECT public.my_workspace_ids()));
CREATE POLICY templates_update ON public.templates FOR UPDATE USING (workspace_id IN (SELECT public.my_workspace_ids())) WITH CHECK (workspace_id IN (SELECT public.my_workspace_ids()));
CREATE POLICY api_keys_ws               ON public.api_keys             FOR ALL USING (workspace_id IN (SELECT public.my_workspace_ids())) WITH CHECK (workspace_id IN (SELECT public.my_workspace_ids()));

CREATE POLICY workspace_invites_ws ON public.workspace_invites FOR ALL USING (workspace_id IN (SELECT public.my_workspace_ids())) WITH CHECK (workspace_id IN (SELECT public.my_workspace_ids()));
CREATE POLICY workspace_sending_defaults_ws ON public.workspace_sending_defaults FOR ALL USING (workspace_id IN (SELECT public.my_workspace_ids())) WITH CHECK (workspace_id IN (SELECT public.my_workspace_ids()));
CREATE POLICY notification_preferences_ws ON public.notification_preferences FOR ALL USING (workspace_id IN (SELECT public.my_workspace_ids())) WITH CHECK (workspace_id IN (SELECT public.my_workspace_ids()));
CREATE POLICY audit_log_ws_read ON public.audit_log FOR SELECT USING (workspace_id IN (SELECT public.my_workspace_ids()));

-- ============================================================
-- AUTO-CREATE WORKSPACE + PROFILE ON SIGNUP
-- ============================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_workspace_id UUID;
    v_name         TEXT;
BEGIN
    v_name := COALESCE(NEW.raw_user_meta_data->>'full_name', split_part(NEW.email, '@', 1), 'My Workspace');

    INSERT INTO public.user_profiles (id, display_name) VALUES (NEW.id, v_name);

    INSERT INTO public.workspaces (owner_id, name) VALUES (NEW.id, v_name) RETURNING id INTO v_workspace_id;

    INSERT INTO public.workspace_members (workspace_id, user_id, role) VALUES (v_workspace_id, NEW.id, 'owner');

    RETURN NEW;
END;
$$;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'on_auth_user_created') THEN
        CREATE TRIGGER on_auth_user_created
            AFTER INSERT ON auth.users
            FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
    END IF;
END; $$;

-- workspace_id column defaults (convenience only — RLS WITH CHECK is the real guard)
ALTER TABLE public.accounts             ALTER COLUMN workspace_id SET DEFAULT public.get_my_workspace_id();
ALTER TABLE public.campaigns            ALTER COLUMN workspace_id SET DEFAULT public.get_my_workspace_id();
ALTER TABLE public.leads                ALTER COLUMN workspace_id SET DEFAULT public.get_my_workspace_id();
ALTER TABLE public.lead_lists           ALTER COLUMN workspace_id SET DEFAULT public.get_my_workspace_id();
ALTER TABLE public.action_log           ALTER COLUMN workspace_id SET DEFAULT public.get_my_workspace_id();
ALTER TABLE public.messages             ALTER COLUMN workspace_id SET DEFAULT public.get_my_workspace_id();
ALTER TABLE public.approval_queue       ALTER COLUMN workspace_id SET DEFAULT public.get_my_workspace_id();
ALTER TABLE public.daily_campaign_stats ALTER COLUMN workspace_id SET DEFAULT public.get_my_workspace_id();
ALTER TABLE public.outbox_events        ALTER COLUMN workspace_id SET DEFAULT public.get_my_workspace_id();

-- ============================================================
-- GRANTS
-- ============================================================
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON ALL TABLES    IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON ALL ROUTINES  IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

-- ============================================================
-- DATA RETENTION POLICY (GDPR)
-- ============================================================
-- GDPR erasure for a lead:
--   UPDATE messages SET message_text='[redacted]', sender_name='[redacted]' WHERE lead_id=<id>;
--   UPDATE leads SET email=NULL, first_name=NULL, last_name=NULL, status='opted_out' WHERE id=<id>;
--   Do NOT delete the leads row — opted_out acts as suppression to prevent re-import.
-- GDPR workspace deletion: ON DELETE CASCADE from workspaces handles all child rows.
-- Retention: DELETE FROM action_log WHERE executed_at < NOW() - INTERVAL '90 days';
-- ============================================================
-- ============================================================
-- AI KNOWLEDGE BASE SCHEMA (Personas, Objections, Assets, Synthesis)
-- ============================================================

-- Create pgvector extension if not exists
CREATE EXTENSION IF NOT EXISTS vector;

-- Personas Table
CREATE TABLE IF NOT EXISTS public.personas (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id UUID NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    pain_points JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Objections Table
CREATE TABLE IF NOT EXISTS public.objections (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id UUID NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
    trigger TEXT NOT NULL,
    playbook TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Knowledge Assets Table (For UI reference)
CREATE TABLE IF NOT EXISTS public.knowledge_assets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id UUID NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'synced',
    source_url TEXT,
    error_msg TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_workspace_url UNIQUE (workspace_id, source_url)
);

-- Vector Chunks Table (Using pgvector)
CREATE TABLE IF NOT EXISTS public.knowledge_chunks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id UUID NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
    asset_id UUID NOT NULL REFERENCES public.knowledge_assets(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    embedding vector(1536), -- Assuming OpenAI ada-002 dimension
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS knowledge_chunks_embedding_idx ON public.knowledge_chunks USING hnsw (embedding vector_cosine_ops);
CREATE INDEX IF NOT EXISTS idx_kc_asset_id ON public.knowledge_chunks(asset_id);
CREATE INDEX IF NOT EXISTS idx_kc_workspace_id ON public.knowledge_chunks(workspace_id);

-- Synthesis Table (One per workspace)
CREATE TABLE IF NOT EXISTS public.knowledge_synthesis (
    workspace_id UUID PRIMARY KEY REFERENCES public.workspaces(id) ON DELETE CASCADE,
    core_value_prop TEXT,
    identified_tone JSONB DEFAULT '[]'::jsonb,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ============================================================

ALTER TABLE public.personas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.objections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.knowledge_assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.knowledge_chunks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.knowledge_synthesis ENABLE ROW LEVEL SECURITY;

-- Personas
CREATE POLICY personas_ws_read ON public.personas FOR SELECT USING (workspace_id IN (SELECT public.my_workspace_ids()));
CREATE POLICY personas_ws_insert ON public.personas FOR INSERT WITH CHECK (workspace_id IN (SELECT public.my_workspace_ids()));
CREATE POLICY personas_ws_update ON public.personas FOR UPDATE USING (workspace_id IN (SELECT public.my_workspace_ids())) WITH CHECK (workspace_id IN (SELECT public.my_workspace_ids()));
CREATE POLICY personas_ws_delete ON public.personas FOR DELETE USING (workspace_id IN (SELECT public.my_workspace_ids()));

-- Objections
CREATE POLICY objections_ws_read ON public.objections FOR SELECT USING (workspace_id IN (SELECT public.my_workspace_ids()));
CREATE POLICY objections_ws_insert ON public.objections FOR INSERT WITH CHECK (workspace_id IN (SELECT public.my_workspace_ids()));
CREATE POLICY objections_ws_update ON public.objections FOR UPDATE USING (workspace_id IN (SELECT public.my_workspace_ids())) WITH CHECK (workspace_id IN (SELECT public.my_workspace_ids()));
CREATE POLICY objections_ws_delete ON public.objections FOR DELETE USING (workspace_id IN (SELECT public.my_workspace_ids()));

-- Assets
CREATE POLICY assets_ws_read ON public.knowledge_assets FOR SELECT USING (workspace_id IN (SELECT public.my_workspace_ids()));
CREATE POLICY assets_ws_insert ON public.knowledge_assets FOR INSERT WITH CHECK (workspace_id IN (SELECT public.my_workspace_ids()));
CREATE POLICY assets_ws_update ON public.knowledge_assets FOR UPDATE USING (workspace_id IN (SELECT public.my_workspace_ids())) WITH CHECK (workspace_id IN (SELECT public.my_workspace_ids()));
CREATE POLICY assets_ws_delete ON public.knowledge_assets FOR DELETE USING (workspace_id IN (SELECT public.my_workspace_ids()));

-- Chunks
CREATE POLICY chunks_ws_read ON public.knowledge_chunks FOR SELECT USING (workspace_id IN (SELECT public.my_workspace_ids()));
CREATE POLICY chunks_ws_insert ON public.knowledge_chunks FOR INSERT WITH CHECK (workspace_id IN (SELECT public.my_workspace_ids()));
CREATE POLICY chunks_ws_update ON public.knowledge_chunks FOR UPDATE USING (workspace_id IN (SELECT public.my_workspace_ids())) WITH CHECK (workspace_id IN (SELECT public.my_workspace_ids()));
CREATE POLICY chunks_ws_delete ON public.knowledge_chunks FOR DELETE USING (workspace_id IN (SELECT public.my_workspace_ids()));

-- Synthesis
CREATE POLICY synthesis_ws_read ON public.knowledge_synthesis FOR SELECT USING (workspace_id IN (SELECT public.my_workspace_ids()));
CREATE POLICY synthesis_ws_insert ON public.knowledge_synthesis FOR INSERT WITH CHECK (workspace_id IN (SELECT public.my_workspace_ids()));
CREATE POLICY synthesis_ws_update ON public.knowledge_synthesis FOR UPDATE USING (workspace_id IN (SELECT public.my_workspace_ids())) WITH CHECK (workspace_id IN (SELECT public.my_workspace_ids()));
CREATE POLICY synthesis_ws_delete ON public.knowledge_synthesis FOR DELETE USING (workspace_id IN (SELECT public.my_workspace_ids()));

-- Defaults
ALTER TABLE public.personas ALTER COLUMN workspace_id SET DEFAULT public.get_my_workspace_id();
ALTER TABLE public.objections ALTER COLUMN workspace_id SET DEFAULT public.get_my_workspace_id();
ALTER TABLE public.knowledge_assets ALTER COLUMN workspace_id SET DEFAULT public.get_my_workspace_id();
ALTER TABLE public.knowledge_chunks ALTER COLUMN workspace_id SET DEFAULT public.get_my_workspace_id();


-- Added from migration 013_campaign_accounts.sql
CREATE TABLE IF NOT EXISTS public.campaign_accounts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    campaign_id UUID NOT NULL REFERENCES public.campaigns(id) ON DELETE CASCADE,
    account_id UUID NOT NULL REFERENCES public.accounts(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(campaign_id, account_id)
);

CREATE INDEX IF NOT EXISTS idx_campaign_accounts_campaign_id ON public.campaign_accounts(campaign_id);
CREATE INDEX IF NOT EXISTS idx_campaign_accounts_account_id ON public.campaign_accounts(account_id);

ALTER TABLE public.campaign_accounts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "campaign_accounts_ws" ON public.campaign_accounts
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.campaigns c 
      WHERE c.id = campaign_accounts.campaign_id
        AND c.workspace_id = ANY(public.my_workspace_ids())
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.campaigns c 
      WHERE c.id = campaign_accounts.campaign_id
        AND c.workspace_id = ANY(public.my_workspace_ids())
    )
  );

-- Added from migration 003_aggregate_rate_limiting.sql
CREATE TABLE IF NOT EXISTS public.action_type_limits (
    action_type text NOT NULL PRIMARY KEY,
    daily_limit integer NOT NULL,
    tier integer NOT NULL DEFAULT 3,
    description text
);

CREATE TABLE IF NOT EXISTS public.account_daily_action_counts (
    id           uuid    NOT NULL DEFAULT gen_random_uuid(),
    account_id   uuid    NOT NULL REFERENCES public.accounts(id) ON DELETE CASCADE,
    action_type  text    NOT NULL REFERENCES public.action_type_limits (action_type),
    usage_date   date    NOT NULL DEFAULT CURRENT_DATE,
    count        integer NOT NULL DEFAULT 0,
    CONSTRAINT account_daily_action_counts_pkey PRIMARY KEY (id),
    CONSTRAINT account_daily_action_counts_unique
        UNIQUE (account_id, action_type, usage_date)
);

CREATE INDEX IF NOT EXISTS account_daily_action_counts_account_date_idx
    ON public.account_daily_action_counts (account_id, usage_date);

ALTER TABLE public.account_daily_action_counts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "account_daily_action_counts_ws" ON public.account_daily_action_counts
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.accounts a 
      WHERE a.id = account_daily_action_counts.account_id
        AND a.workspace_id = ANY(public.my_workspace_ids())
    )
  );

-- Added from migration 003_processing_jobs.sql
CREATE TABLE IF NOT EXISTS public.processing_jobs (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  asset_id     UUID REFERENCES public.knowledge_assets(id) ON DELETE CASCADE,
  job_type     TEXT NOT NULL,
  status       TEXT NOT NULL DEFAULT 'pending',
  payload      JSONB NOT NULL DEFAULT '{}',
  error_msg    TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS processing_jobs_status_idx ON public.processing_jobs (status, created_at);
CREATE INDEX IF NOT EXISTS idx_pj_asset_id ON public.processing_jobs(asset_id);

ALTER TABLE public.processing_jobs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "processing_jobs_ws" ON public.processing_jobs
  FOR ALL USING (workspace_id = ANY(public.my_workspace_ids()));


-- ==============================================================================
-- WORKSPACE USAGE (Financial Limits)
-- ==============================================================================
CREATE TABLE public.workspace_usage (
    workspace_id UUID PRIMARY KEY REFERENCES public.workspaces(id) ON DELETE CASCADE,
    ai_requests_this_month INT DEFAULT 0 NOT NULL,
    leads_scraped_this_month INT DEFAULT 0 NOT NULL,
    billing_tier TEXT DEFAULT 'free' NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc', now()) NOT NULL
);

CREATE INDEX idx_workspace_usage_workspace_id ON public.workspace_usage(workspace_id);

CREATE OR REPLACE FUNCTION public.increment_usage(p_workspace_id UUID, p_type TEXT, p_amount INT, p_limit INT)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    v_current INT;
    v_new INT;
BEGIN
    INSERT INTO public.workspace_usage (workspace_id)
    VALUES (p_workspace_id)
    ON CONFLICT (workspace_id) DO NOTHING;
    
    SELECT ai_requests_this_month, leads_scraped_this_month 
    INTO v_current, v_new
    FROM public.workspace_usage
    WHERE workspace_id = p_workspace_id
    FOR UPDATE;

    IF p_type = 'ai' THEN
        v_current := (SELECT ai_requests_this_month FROM public.workspace_usage WHERE workspace_id = p_workspace_id);
        IF v_current + p_amount > p_limit THEN
            RAISE EXCEPTION 'UsageLimitExceededError: AI limit % exceeded by %', p_limit, (v_current + p_amount);
        END IF;
        
        UPDATE public.workspace_usage
        SET ai_requests_this_month = ai_requests_this_month + p_amount,
            updated_at = timezone('utc', now())
        WHERE workspace_id = p_workspace_id;
        
    ELSIF p_type = 'leads' THEN
        v_current := (SELECT leads_scraped_this_month FROM public.workspace_usage WHERE workspace_id = p_workspace_id);
        IF v_current + p_amount > p_limit THEN
            RAISE EXCEPTION 'UsageLimitExceededError: Leads limit % exceeded by %', p_limit, (v_current + p_amount);
        END IF;
        
        UPDATE public.workspace_usage
        SET leads_scraped_this_month = leads_scraped_this_month + p_amount,
            updated_at = timezone('utc', now())
        WHERE workspace_id = p_workspace_id;
        
    ELSE
        RAISE EXCEPTION 'Unknown usage type: %', p_type;
    END IF;
END;
$$;
