# THIS FILE IS AUTOGENERATED FROM SUPABASE OPENAPI SPEC
# DO NOT EDIT MANUALLY

from typing import Literal, TypedDict, Optional

TableNames = Literal[
    "workspaces", "list_members", "workspace_members", "subscriptions", "proxies", "leads", "outbox_events", "knowledge_chunks", "daily_campaign_stats", "templates", "accounts", "knowledge_assets", "campaigns", "knowledge_synthesis", "action_log", "user_profiles", "lead_states", "messages", "objections", "lead_lists", "approval_queue", "personas", "api_keys", "admin_grants"
]

WorkspacesColumns = Literal[
    "id", "owner_id", "name", "tier", "stripe_customer_id", "created_at", "updated_at", "hubspot_token"
]

class WorkspacesRow(TypedDict, total=False):
    id: str
    owner_id: str
    name: str
    tier: str
    stripe_customer_id: str
    created_at: str
    updated_at: str
    hubspot_token: str


List_membersColumns = Literal[
    "id", "list_id", "opportunity_id"
]

class List_membersRow(TypedDict, total=False):
    id: str
    list_id: str
    opportunity_id: str


Account_daily_usageColumns = Literal[
    "account_id", "usage_date", "connections_sent", "messages_sent"
]

class Account_daily_usageRow(TypedDict, total=False):
    account_id: str
    usage_date: str
    connections_sent: int
    messages_sent: int


Workspace_membersColumns = Literal[
    "id", "workspace_id", "user_id", "role", "invited_by", "created_at"
]

class Workspace_membersRow(TypedDict, total=False):
    id: str
    workspace_id: str
    user_id: str
    role: str
    invited_by: str
    created_at: str


SubscriptionsColumns = Literal[
    "id", "workspace_id", "stripe_subscription_id", "stripe_price_id", "status", "tier", "current_period_start", "current_period_end", "cancel_at_period_end", "canceled_at", "trial_end", "raw_stripe_event", "created_at", "updated_at"
]

class SubscriptionsRow(TypedDict, total=False):
    id: str
    workspace_id: str
    stripe_subscription_id: str
    stripe_price_id: str
    status: str
    tier: str
    current_period_start: str
    current_period_end: str
    cancel_at_period_end: bool
    canceled_at: str
    trial_end: str
    raw_stripe_event: Any
    created_at: str
    updated_at: str


ProxiesColumns = Literal[
    "id", "workspace_id", "provider", "host", "port", "username", "secret_ref", "protocol", "country_code", "status", "last_checked_at", "created_at", "updated_at"
]

class ProxiesRow(TypedDict, total=False):
    id: str
    workspace_id: str
    provider: str
    host: str
    port: int
    username: str
    secret_ref: str
    protocol: str
    country_code: str
    status: str
    last_checked_at: str
    created_at: str
    updated_at: str


LeadsColumns = Literal[
    "id", "workspace_id", "first_name", "last_name", "linkedin_url", "company_name", "email", "domain", "job_title", "company_description", "location", "industry", "mutual_connections", "enrichment_source", "status", "metadata", "created_at", "updated_at"
]

class LeadsRow(TypedDict, total=False):
    id: str
    workspace_id: str
    first_name: str
    last_name: str
    linkedin_url: str
    company_name: str
    email: str
    domain: str
    job_title: str
    company_description: str
    location: str
    industry: str
    mutual_connections: str
    enrichment_source: str
    status: str
    metadata: Any
    created_at: str
    updated_at: str


Outbox_eventsColumns = Literal[
    "id", "workspace_id", "event_type", "payload", "idempotency_key", "status", "attempts", "last_error", "deliver_at", "delivered_at", "created_at"
]

class Outbox_eventsRow(TypedDict, total=False):
    id: str
    workspace_id: str
    event_type: str
    payload: Any
    idempotency_key: str
    status: str
    attempts: int
    last_error: str
    deliver_at: str
    delivered_at: str
    created_at: str


Knowledge_chunksColumns = Literal[
    "id", "workspace_id", "asset_id", "content", "embedding", "created_at"
]

class Knowledge_chunksRow(TypedDict, total=False):
    id: str
    workspace_id: str
    asset_id: str
    content: str
    embedding: str
    created_at: str


Daily_campaign_statsColumns = Literal[
    "id", "workspace_id", "campaign_id", "stat_date", "connections_sent", "messages_sent", "accepted", "replied"
]

class Daily_campaign_statsRow(TypedDict, total=False):
    id: str
    workspace_id: str
    campaign_id: str
    stat_date: str
    connections_sent: int
    messages_sent: int
    accepted: int
    replied: int


TemplatesColumns = Literal[
    "id", "workspace_id", "name", "description", "nodes_json", "edges_json", "status", "tags", "downloads", "created_at", "updated_at"
]

class TemplatesRow(TypedDict, total=False):
    id: str
    workspace_id: str
    name: str
    description: str
    nodes_json: Any
    edges_json: Any
    status: str
    tags: list
    downloads: int
    created_at: str
    updated_at: str


AccountsColumns = Literal[
    "id", "workspace_id", "proxy_id", "name", "linkedin_profile_url", "session_cookies_encrypted", "daily_connection_limit", "daily_message_limit", "is_warmup", "warmup_start_date", "warmup_target_days", "warmup_max_connections", "warmup_max_messages", "status", "last_health_check_at", "cookie_expires_at", "created_at", "updated_at", "is_active", "daily_scrape_count", "last_scrape_date"
]

class AccountsRow(TypedDict, total=False):
    id: str
    workspace_id: str
    proxy_id: str
    name: str
    linkedin_profile_url: str
    session_cookies_encrypted: str
    daily_connection_limit: int
    daily_message_limit: int
    is_warmup: bool
    warmup_start_date: str
    warmup_target_days: int
    warmup_max_connections: int
    warmup_max_messages: int
    status: str
    last_health_check_at: str
    cookie_expires_at: str
    created_at: str
    updated_at: str
    is_active: bool
    daily_scrape_count: int
    last_scrape_date: str


Knowledge_assetsColumns = Literal[
    "id", "workspace_id", "name", "type", "status", "created_at"
]

class Knowledge_assetsRow(TypedDict, total=False):
    id: str
    workspace_id: str
    name: str
    type: str
    status: str
    created_at: str


CampaignsColumns = Literal[
    "id", "workspace_id", "name", "status", "nodes_json", "edges_json", "sender_account_ids_json", "metadata", "created_at", "updated_at"
]

class CampaignsRow(TypedDict, total=False):
    id: str
    workspace_id: str
    name: str
    status: str
    nodes_json: Any
    edges_json: Any
    sender_account_ids_json: Any
    metadata: Any
    created_at: str
    updated_at: str


Knowledge_synthesisColumns = Literal[
    "workspace_id", "core_value_prop", "identified_tone", "updated_at"
]

class Knowledge_synthesisRow(TypedDict, total=False):
    workspace_id: str
    core_value_prop: str
    identified_tone: Any
    updated_at: str


Action_logColumns = Literal[
    "id", "workspace_id", "account_id", "lead_state_id", "action_type", "result", "error_detail", "metadata", "executed_at"
]

class Action_logRow(TypedDict, total=False):
    id: str
    workspace_id: str
    account_id: str
    lead_state_id: str
    action_type: str
    result: str
    error_detail: str
    metadata: Any
    executed_at: str


User_profilesColumns = Literal[
    "id", "display_name", "avatar_url", "created_at", "updated_at"
]

class User_profilesRow(TypedDict, total=False):
    id: str
    display_name: str
    avatar_url: str
    created_at: str
    updated_at: str


Lead_statesColumns = Literal[
    "id", "campaign_id", "opportunity_id", "current_node_id", "status", "next_run_at", "variables_json", "error_reason", "attempts", "max_attempts", "updated_at", "created_at"
]

class Lead_statesRow(TypedDict, total=False):
    id: str
    campaign_id: str
    opportunity_id: str
    current_node_id: str
    status: str
    next_run_at: str
    variables_json: Any
    error_reason: str
    attempts: int
    max_attempts: int
    updated_at: str
    created_at: str


MessagesColumns = Literal[
    "id", "workspace_id", "account_id", "lead_id", "sender_name", "message_text", "direction", "intent", "intent_confidence", "created_at", "updated_at"
]

class MessagesRow(TypedDict, total=False):
    id: str
    workspace_id: str
    account_id: str
    lead_id: str
    sender_name: str
    message_text: str
    direction: str
    intent: str
    intent_confidence: Any
    created_at: str
    updated_at: str


ObjectionsColumns = Literal[
    "id", "workspace_id", "trigger", "playbook", "created_at", "updated_at"
]

class ObjectionsRow(TypedDict, total=False):
    id: str
    workspace_id: str
    trigger: str
    playbook: str
    created_at: str
    updated_at: str


Lead_listsColumns = Literal[
    "id", "workspace_id", "name", "type", "row_count", "created_at", "updated_at"
]

class Lead_listsRow(TypedDict, total=False):
    id: str
    workspace_id: str
    name: str
    type: str
    row_count: int
    created_at: str
    updated_at: str


Approval_queueColumns = Literal[
    "id", "workspace_id", "account_id", "sender_name", "thread_messages_json", "intent", "heat_score", "ai_draft", "status", "reviewed_at", "created_at", "updated_at"
]

class Approval_queueRow(TypedDict, total=False):
    id: str
    workspace_id: str
    account_id: str
    sender_name: str
    thread_messages_json: Any
    intent: str
    heat_score: Any
    ai_draft: str
    status: str
    reviewed_at: str
    created_at: str
    updated_at: str


PersonasColumns = Literal[
    "id", "workspace_id", "title", "pain_points", "created_at", "updated_at"
]

class PersonasRow(TypedDict, total=False):
    id: str
    workspace_id: str
    title: str
    pain_points: Any
    created_at: str
    updated_at: str


Api_keysColumns = Literal[
    "id", "workspace_id", "name", "key_hash", "key_prefix", "last_used_at", "expires_at", "is_active", "created_at"
]

class Api_keysRow(TypedDict, total=False):
    id: str
    workspace_id: str
    name: str
    key_hash: str
    key_prefix: str
    last_used_at: str
    expires_at: str
    is_active: bool
    created_at: str


Admin_grantsColumns = Literal[
    "id", "user_id", "granted_by", "granted_at", "revoked_at", "revoked_by", "reason"
]

class Admin_grantsRow(TypedDict, total=False):
    id: str
    user_id: str
    granted_by: str
    granted_at: str
    revoked_at: str
    revoked_by: str
    reason: str
